<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PricingSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('shipment_types')->insert([
            [
                'name' => 'Products & Food',
                'name_ar' => 'منتجات وطعام',
                'category' => 'products',
                'base_price' => 50.00,
                'description' => 'Standard products and food delivery',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Products & Food (Oversize)',
                'name_ar' => 'منتجات وطعام (أوفر سايز)',
                'category' => 'products_oversize',
                'base_price' => 75.00,
                'description' => 'Oversized products and food delivery',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Birds (Small)',
                'name_ar' => 'عصافير',
                'category' => 'birds_small',
                'base_price' => 75.00,
                'description' => 'Small birds delivery',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Birds (Multiple)',
                'name_ar' => 'بعض العصافير',
                'category' => 'birds_multiple',
                'base_price' => 100.00,
                'description' => 'Multiple birds delivery',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cats',
                'name_ar' => 'قطط',
                'category' => 'cats',
                'base_price' => 100.00,
                'description' => 'Cat delivery',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dogs',
                'name_ar' => 'كلاب',
                'category' => 'dogs',
                'base_price' => 150.00,
                'description' => 'Dog delivery',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Plants (Small)',
                'name_ar' => 'شتلات (صغيرة)',
                'category' => 'plants_small',
                'base_price' => 50.00,
                'description' => 'Small plants delivery',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Plants (Multiple)',
                'name_ar' => 'شتلات (متعددة)',
                'category' => 'plants_multiple',
                'base_price' => 75.00,
                'description' => 'Multiple plants delivery',
                'is_active' => true,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('delivery_zones')->insert([
            [
                'name' => 'Abu Dhabi',
                'name_ar' => 'أبوظبي',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dubai',
                'name_ar' => 'دبي',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sharjah',
                'name_ar' => 'الشارقة',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ajman',
                'name_ar' => 'عجمان',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Umm Al Quwain',
                'name_ar' => 'أم القيوين',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ras Al Khaimah',
                'name_ar' => 'رأس الخيمة',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fujairah',
                'name_ar' => 'الفجيرة',
                'zone_type' => 'standard',
                'additional_fee' => 0.00,
                'areas' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hatta & Suburbs',
                'name_ar' => 'حتا وضواحيها',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Hatta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sha\'am',
                'name_ar' => 'شعم',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Sha\'am',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Al Jaeer',
                'name_ar' => 'الجير',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Al Jaeer',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Al Khatam',
                'name_ar' => 'الختم',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Al Khatam',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Razeen',
                'name_ar' => 'رزين',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Razeen',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Al Saad',
                'name_ar' => 'الساد',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Al Saad',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ramah',
                'name_ar' => 'رماح',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Ramah',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sweihan',
                'name_ar' => 'سويحان',
                'zone_type' => 'premium',
                'additional_fee' => 25.00,
                'areas' => 'Sweihan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
